### PR TITLE
Remove build path from project.json

### PR DESCRIPTION
**Pull request by daveaspinall**
Removing the build path from the project.json config file to remove any confusion over where files will be built.

Expansions will need to be updated to make sure this isn't a breaking change.

### CODE REVIEW

**Comment by daveaspinall** [comment]
@bmds Should be good to merge this now. Please could you double check?

**Comment by tawashley** [comment]
Is this meant to also include the work on removing the Sass files? Is so, then LGTM (after your double check) 👍

**Comment by daveaspinall** [comment]
I probably should have created a separate pull request for removing the Sass files 🙈

**Comment by tawashley** [comment]
As long as the release notes for cartridge reflect both changes, I can't foresee this being a major issue

**Pull request merged**
